language: node_js
node_js:
- 'stable'
- '6'
- '4'
cache:
  directories:
  - node_modules

# Build docs using latest docpress plugins
script:
- npm install
- npm install docpress
- ./bin/docpress build

# Deploy to gh-pages
after_success:
- npm run coveralls
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./node_modules/.bin/git-update-ghpages -e; fi

env:
  global:
  - GIT_NAME: Frank Lin
  - GIT_EMAIL: flinhong@hotmail.com
  - GITHUB_REPO: flinhong/jieri
  - GIT_SOURCE: _docpress
  - GIT_BRANCH: gh-pages
